{% set version = "0.8.1.2360" %}
{% set lib_version = version.split(".")[0]+"."+version.split(".")[1]+"."+version.split(".")[2] %}
{% set platform = "placeholder" %}  # [not (linux64 or aarch64)]
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}    # [aarch64]
{% set extension = "tar.xz" %}

{% set cuda_compiler_version = cuda_compiler_version|default("None") %}
{% set cuda_major = environ.get("cuda_compiler_version", "13.0").split(".")[0] %}

package:
  name: libcublasmp-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cublasmp/redist/libcublasmp/{{ platform }}/libcublasmp-{{ platform }}-{{ version }}_cuda{{ cuda_major }}-archive.{{ extension }}
  sha256: 25bb1de955d4fb45e25d1adc192c1f872c8a4664e10fa73129d819d0fc310889  # [linux64 and (cuda_compiler_version or "").startswith("12")]
  sha256: e13bca48bca81bd5f6e932d89f1b88e2545beb7d4284814b2b430581183df7ee  # [linux64 and (cuda_compiler_version or "").startswith("13")]
  sha256: fe9237eaea88aa45d0eccbe0eead419d71fa6c6206dcbd3fe1e929d571bc7fb9  # [aarch64 and (cuda_compiler_version or "").startswith("12")]
  sha256: 971b4f0e24de7171347b57204c91d204263d2d179d0048a93042aaebcea68f81  # [aarch64 and (cuda_compiler_version or "").startswith("13")]

build:
  number: 0
  skip: true  # [cuda_compiler_version in (None, "None") or (cuda_compiler_version or "").startswith("11")]
  skip: true  # [not (linux64 or aarch64)]
  script:
    - check-glibc lib/*.so.*
    - cp -rv include $PREFIX
    - cp -rv lib $PREFIX

requirements:
  build:
    - cf-nvidia-tools 1   # [linux]

outputs:
  - name: libcublasmp
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
       # potentially breaking changes with every minor version until 1.0.0
        - {{ pin_subpackage("libcublasmp", max_pin="x.x") }}
      missing_dso_whitelist:
        - "*libcuda.so*"
    files:
      - lib/libcublasmp.so.*
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_compiler_version }}
        - libcublas
        - nccl
      run:
        - {{ pin_compatible("cuda-version", max_pin="x") }}
        - libcublas
        - nccl
    test:
      commands:
        - test -L $PREFIX/lib/libcublasmp.so.0
        - test -f $PREFIX/lib/libcublasmp.so.{{ lib_version }}
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

  - name: libcublasmp-dev
    build:
      ignore_run_exports:
        - cuda-version
      run_exports:
        - {{ pin_subpackage("libcublasmp", max_pin="x") }}
    files:
      - lib/libcublasmp.so
      - include/cublasmp.h
    requirements:
      host:
        - cuda-version {{ cuda_compiler_version }}
      run:
        - {{ pin_subpackage("libcublasmp", exact=True) }}
    test:
      commands:
        - test -f $PREFIX/include/cublasmp.h
        - test -L $PREFIX/lib/libcublasmp.so
    about:
      home: https://docs.nvidia.com/cuda/cublasmp/
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
      summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
      description: |
        NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
        cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
      doc_url: https://docs.nvidia.com/cuda/cublasmp/

about:
  home: https://docs.nvidia.com/cuda/cublasmp/
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/cublasmp/license/index.html
  summary: NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
  description: |
    NVIDIA cuBLASMp is a high performance, multi-process, GPU accelerated library for distributed basic dense linear algebra.
    cuBLASMp is compatible with 2D block-cyclic data layout and provides PBLAS-like C APIs.
  doc_url: https://docs.nvidia.com/cuda/cublasmp/

extra:
  recipe-maintainers:
    - almogsegal
    - mrogowski
    - conda-forge/cuda
  feedstock-name: libcublasmp
